### ISSUE TITLE
Launch manager not selecting the node

### ISSUE THREAD

**Issue by Mert18** [robolaunch/robot-operator#77]
### What happened?

Launch manager is unexpectedly scheduled a new node. This might be a problem with the node selectors of the launch manager.

### What did you expect to happen?

Launch manager created a new node.

### How can we reproduce it (as minimally and precisely as possible)?

Try to create a launch manager.

### Kubernetes version

--

### Container network interface (CNI) and version

--

**Comment by tunahanertekin** [comment]
Solved in 334a099.
